# Generated by Django 3.2.7 on 2021-09-27 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('H4-0A', 'H4-0A'), ('H4-0B', 'H4-0B'), ('H4-01', 'H4-01'), ('H4-02', 'H4-02'), ('H4-03', 'H4-03'), ('H4-04', 'H4-04'), ('H4-05', 'H4-05'), ('H4-06', 'H4-06'), ('H4-07', 'H4-07'), ('H4-08', 'H4-08'), ('H4-09', 'H4-09'), ('H4-10', 'H4-10'), ('H4-11', 'H4-11'), ('H4-12', 'H4-12'), ('H4-13', 'H4-13'), ('H4-14', 'H4-14'), ('H4-15', 'H4-15'), ('H4-16', 'H4-16'), ('H4-17', 'H4-17'), ('H4-18', 'H4-18'), ('H4-19', 'H4-19'), ('H4-20', 'H4-20'), ('H4-21', 'H4-21'), ('H4-22', 'H4-22'), ('H4-23', 'H4-23'), ('H4-24', 'H4-24'), ('WR-00', 'WR-00'), ('WR-01', 'WR-01'), ('WR-02', 'WR-02'), ('WR-03', 'WR-03'), ('WR-04', 'WR-04'), ('WR-05', 'WR-05'), ('WR-06', 'WR-06'), ('WR-07', 'WR-07'), ('HG-00', 'HG-00'), ('HG-01', 'HG-01'), ('HG-02', 'HG-02'), ('HG-03', 'HG-03'), ('HG-04', 'HG-04'), ('HG-05', 'HG-05'), ('EH1', 'EH1'), ('EH2', 'EH2'), ('EH3', 'EH3'), ('EH4', 'EH4'), ('EH5', 'EH5'), ('EH6', 'EH6'), ('XF0W1', 'XF0W1'), ('XF0W2', 'XF0W2'), ('XF0W3', 'XF0W3'), ('XF0S7', 'XF0S7'), ('SCNA', 'SCNA'), ('SCNB', 'SCNB')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COSMO-SkyMed 1', 'COSMO-SkyMed 1'), ('COSMO-SkyMed 2', 'COSMO-SkyMed 2'), ('COSMO-SkyMed 3', 'COSMO-SkyMed 3'), ('COSMO-SkyMed 4', 'COSMO-SkyMed 4'), ('RADARSAT-2', 'RADARSAT-2')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('StripMap (HIMAGE)', 'StripMap (HIMAGE)'), ('ScanSAR (WideRegion)', 'ScanSAR (WideRegion)'), ('ScanSAR (HugeRegion)', 'ScanSAR (HugeRegion)'), ('High Incidence', 'High Incidence'), ('Extra Fine', 'Extra Fine'), ('ScanSAR Narrow', 'ScanSAR Narrow')], max_length=30)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.satellite')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('polarisation', models.CharField(choices=[('HH', 'HH'), ('VV', 'VV')], max_length=2)),
                ('side', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=5)),
                ('angle', models.FloatField(blank=True, default=(), null=True)),
                ('sensing_start', models.DateTimeField()),
                ('sensing_stop', models.DateTimeField()),
                ('downlink_start', models.DateTimeField(blank=True, null=True)),
                ('downlink_stop', models.DateTimeField(blank=True, null=True)),
                ('scene_number', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(blank=True, max_length=50, null=True)),
                ('beam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.beam')),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.satellite')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='beam',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
    ]
