# Generated by Django 3.2.7 on 2021-09-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_planning_angle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmoSkyMedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('pr_id', models.IntegerField(unique=True)),
                ('polarisation', models.CharField(choices=[('HH', 'HH'), ('VV', 'VV')], max_length=2)),
                ('side', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=5)),
                ('angle', models.FloatField(blank=True, null=True)),
                ('sensing_start', models.DateTimeField()),
                ('sensing_stop', models.DateTimeField()),
                ('visibility_start', models.DateTimeField(blank=True, null=True)),
                ('visibility_stop', models.DateTimeField(blank=True, null=True)),
                ('scene_number', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(blank=True, max_length=50, null=True)),
                ('beam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.beam')),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.satellite')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='RadarsatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('polarisation', models.CharField(choices=[('HH', 'HH'), ('VV', 'VV')], max_length=2)),
                ('side', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=5)),
                ('angle', models.FloatField(blank=True, null=True)),
                ('sensing_start', models.DateTimeField()),
                ('sensing_stop', models.DateTimeField()),
                ('downlink_start', models.DateTimeField(blank=True, null=True)),
                ('downlink_stop', models.DateTimeField(blank=True, null=True)),
                ('scene_number', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(blank=True, max_length=50, null=True)),
                ('beam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.beam')),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.satellite')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
