# Generated by Django 3.2.7 on 2021-09-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210928_2149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cosmoskymedplan',
            table='COSMO-SkyMed Plan',
        ),
        migrations.AlterModelTable(
            name='radarsatplan',
            table='RADARSAT-2 Plan',
        ),
    ]
